# Add the name of the board you are programming
BOARD_TAG     = cm904

# Add the port you will use for the USB connection
MONITOR_PORT  = /dev/ttyACM0

# Fill with the OpenCM folder containing the makefiles and tools here
OPENCMIDE_DIR = ${OpenCM}

# Do not touch this line
include $(OPENCMIDE_DIR)/mk/OpenCM.mk
