#!/bin/bash

# Eventual environment variable to load
export log4j_logger_ros=WARNING
if pgrep -x "roscore" > /dev/null
then
    echo "[BASH Tigrillo]  ROSCORE is already running!"
else
	echo "[BASH Tigrillo]  Starting ROSCORE!"
    roscore &
fi

N_CORES=1
export ROS_IP=`hostname -I`

# Run the software with eventual parameters overload
if [ "$1" = "optim" ];
then
	python3 main.py -c ../../data/configs/sim/feet_optim.conf "${@:2}"
else
	python3 main.py -c ../../data/configs/sim/feet.conf "$@"
fi

# Kill any running gazebo instance (security in case an exception is not taken into account)
pkill gzserver
pkill gzclient